service: serverless-api-example

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs6.10
  region: us-east-1
  stage: v1
  deploymentBucket: ${env:DEPLOYMENT_BUCKET}

functions:
  microservice:
    name: serverless-api-example-${self:provider.stage}
    description: Microservice to Hello World
    handler: src/handler.app
    events:
      - http:
          method: GET
          path: loans
          cors: true
      - http:
          method: GET
          path: proxy-example
          cors: true

custom:
  stage: "${opt:stage, self:provider.stage}"

package:
  exclude:
    - .vscode/**
    - .scripts/**
    - tests/**
    - coverage/**
    - .travis.yml
    - README.md